language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
- ls ./build
deploy:
  provider: s3
  access_key_id: AKIAIGWRXLWWJ2QAYE4A
  secret_access_key:
    secure: CmeTreu2jUwYU11tb/+KRCL5lzjtz84B9XYF+thn2V5kUu0ildkXE4UGmvdoOkEHrghb1wh9EJetJVmmK+J0TICj36MpuQfNoqH1tQReUVFHofttiS6yq4hRPV+5FeUoES1KLPrah6ka0DIidAiFusdZNzYIvmbkTvSiOrwfzgSlG8zzsmpdhHbGB1xP6y7UehqN+RcwBfzMy/qXPmiVZ5uoA5yhK7EwBR04ETewUfNBxNS98rEQd8vb35z+b/grwPCPI309prrxsn9jBTA3eDCsJbyd6j/t8rlaVPI2EtN9BT3emRiMp7dBkYoj6ZUB2sIa9K4cih/zOCdTbdz+fZmoOI6xVs8bs7zC/LdC7CSpEPgNzSBDdYiTanVB5Lk0e1+uccxVYwwCVD9P10VUKIsk3xeeCaykuLAiM1MmLeThJjLhZIk7s0YQVkF3+rO99Y0VTWyVn9TgrZEDoPI2Mwk3on0ddTjUHqx7lb4Qy2aAoin2UmFrPdkYv+G4DNKmTMdv3CUKZr74bY+2mMQlZ/jVg5AOapCG9ju9gQ0qhFfQtG/b/dBLRFo/Weyt3Vd6kGM3J2MEQ8L9RBxghJ3OuLJ0mvf4BaBJzoWFQbFUNpewNLZE+z/B5VHXnFBB0yJ8hMOrpW9f0yG9dG+2zhHtYVZhox1FQ0gZBHCdjCuPPQY=
  bucket: zachhuxford-io
  skip_cleanup: true
  region: ap-southeast-2
  local-dir: build
  acl: public_read
  on:
    repo: zachbwh/zachhuxford.io