language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
- ls ./build
deploy:
  provider: s3
  access_key_id: AKIAIGWRXLWWJ2QAYE4A
  secret_access_key:
    secure: FzAW5zHrpgmeqZ7pZXZg3p+Stl3gWe2SgEpg5uaCfeRtce0ucmaQIP0DqEr1meX0gXANE88+g/Zpxo9QihVzzXA6tAZ3sn7cWmQWIWAOdY+95VU91DzBLcxdgTb2O5E5KOQMgcBb0+fo63QuLjuNa5HL8aSvMxn83BM4E0K7IFD8oARhZChZ2xpy7XKanamThJ3bA9+VA3hYJcSdvZPL4MVvqCqo05MkPZqPD0SqRlwcjJSa5ZQgewI1taRezF5ZzIQUoTmklYBIr6LqlEdMPZ7soxs/KJWKz/1FeavFGEZJu85ae5Q5gVO/ryQEhNK7LDidFvVKPhn/e/yYliFHYwhp0EOazYmRzdDH7R29rQa2BZ0u+VL16DbkeWhYSlVacyhJ4ZL8Fgwehr/6mnjGWrFpa7D77qgybtEkL1DfH0tsUdfTtZh3TbG/w24axa6+sSoxC42hwafX0mBZQnkwvRqPyqYDta7WXJ2/too7fNh5+ED7LkzFmjoHUgLEKVyLrm84h5Pvig73Z81/OMCXPWlVq1EBwe8DDgPsfPkYXOkMyeCFF83YLzD2gzgZ8DWpZAIOHtojFXP13BHYwWDqATxkaVjolhQaRRJxr6wzyp0jTJzqpB8CaOIH98b8TFNQFUpRDTKsVWXBw+8zEJLdo72wQ4s/lWthwCths2ewEi0=
  bucket: zachhuxford-io
  skip_cleanup: true
  region: ap-southeast-2
  local-dir: build
  acl: public_read
  on:
    repo: zachbwh/zachhuxford.io