language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
- ls ./build
deploy:
  provider: s3
  access_key_id: AKIAIGWRXLWWJ2QAYE4A
  secret_access_key:
    secure: WYLErsJcu4tXil4QhqeuFSeSshHTJOe5UXsGkZmD9K3oK+F7yurSx8831rGTpMdTOFHSzrw6v9p4SOqDM8v7JwpT+vhTyhGZJKVxg4hRLbx9Jnch/v4eB8CPG+hhUKbw7R92sn6kw/pLqRO99LWutzQdVlKCk/xflWBlgDpnOwcrhbiC4XxhTMRTpMLCo6lXHOVuZMvyihWYcMqoT1i6BDnScayRGerkbTZXjrUHUgptb9hYIMLnlJTOc1Cui7n0EUYZgvTu0aKee80eXXi4KWe8z3TEK8zhdMnazWFhw63LBflmc3xMOqp5gqGAkow7UbXqMBehkg+4ezdSk52P1Bw8tpZaOBLwsvLzdOGZUWhFoCgayMMBvx85JMEL+ZM26XouBrPl9gaiiWYPuR+eIgImRJ0SjuL1L+2W7eqtg8s7Z5yRx2OcR0Xa/YifzA3EGdt73e91OKHnZMn3GFcKpLPjrL104Zx1rKD/B/qvrpJussSNRpePoAGVQn3NRwqS9IOsNh3jQrrRqc/7Q5x6RO867IpYrzo1d358tm+bUn0eDKl0TKM1OQ9+O/2UW3dEkyFvzdF0+pXQHixdiwMlAmFdDh/CZkDHrfMzcByJwUXolUv+O9s1nPq8ax4wJZ+V4ttrHZ1uSfILisihc+L2xS2mlN2pyIR9qCdr+WE+4fU=
  bucket: zachhuxford-io
  skip_cleanup: true
  region: ap-southeast-2
  local-dir: build
  acl: public_read
  on:
    repo: zachbwh/zachhuxford.io
