language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
- ls ./build
deploy:
  provider: s3
  access_key_id: AKIAIGWRXLWWJ2QAYE4A
  secret_access_key:
    secure: kCQqpJ37ZYud1gBJETPY1T6DYkSbVeTgh0hX+uCMPgNnetpT/WCqC7igRspabNiFWnIhswF/iaCWbzguX1UbhGuRf13OFA6sqiiqiAKW3BlaurWxvvxAuZYiV6PWKW9aA2Yz0CQcaQRTs+6oB+/1qY1iW7hrhuAfUhr/3uKS4alrzC4Q4IjBboPiJPF5MqMl1di6rerAAjEf16Z3F0o0FyYoBkClj+rOKFQqFev9aZhPhjfsgcUQGjKnuF99/YKaVj2vjGrWotluhPUwOlMmm+x+/nCG4+gzqEQY7V1TYpCNgz5b0GFL5GauS2WbuNZPDm6dZ4t5cCw2yWSDTJXx7x+sZCJWMUCJ0kXIrY97YVs1w5xhzUuEuWw65Ax9i3URgmPSlDj+KGSMeoTsPaz7IMDq/M9mHQm5u3DtAZ8lTEq7IFTLcHUtD/OPL3kHpqnWE27affZudsDLkUkAEdHN/xYKyqNQZtSE6CR6YnbtyAoBsrEjxvivhRxXFSjL1BmQb8sMxDvZt4OA87TpllhbbEgqrK75mSs/OHWrwTopIN1Bo4NqFyvv6I0ybN9anyyEbV35CHHReswO3xQCNOtysU6laygWE55mH0CWhRnTozH+yu3wIsvLAz72S9kBfntuFuIs/0sbSA8J9EoAG0uNLBUztvDCK79opuSDbEa/dtQ=
  bucket: zachhuxford-io
  skip_cleanup: true
  region: ap-southeast-2
  local-dir: build
  acl: public_read
  on:
    repo: zachbwh/zachhuxford.io
