language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
- ls ./build
deploy:
  provider: s3
  access_key_id: AKIAIGWRXLWWJ2QAYE4A
  secret_access_key:
    secure: b6OeEFjHtykAq5+9zGJOkk09Ds2he3nE/PAb2tROVf2i5yfQ2vPzsz0Xt0+SgB7tFK/YEx+lLVkMVIzwl0mZtAgtGnyDCi8JYU25n11NJzAcx3DuSqOUNj6Y/KX/vmC6XCRdK2FWyWdso5+odcAPuNSlD0yEtSHJF1mdsJAkzh52JcUMo+S/a/ehw6vnpoM+8R/BqLGDWAZFUOKytARURG6EMh+ym6qXkrZrh2c9vsMuw5aqGkQ29bdP0CQdeyKD1KhWJNHdm29TnhV2r2jfNjFsNAvAxn2FmB40BHk7aP4nCezCTxWi4oCJaLbobzPCm7FoljNl3y4B6lFCw64q/KtSlnJANXlI0WBCTfRlACgrSeUWakFduI25qVeYZTVlkgl25LZsae939qvDLcbnfzUNBrqRuMTepJ4y7j79sIJ+UFTnyhUQESfkCE7fM+8qh/TgYrY25U541dwHM7/C0DQZr5JmuKss0Q54BHcJTUw0waa46jkLdnCyVcRltZx4VY/C4a6cKw0tKqr05G25ZCP8Gf5T61itb+T82QJ9fS41Ec1Clg1QMDQ7VrkgwkSWPYGGoT608yO3wekIDUV/bYEcCc5yMsWkgBdhz8R6tnA7/tT7ZvFUE8KvlEzwRlmwGBTNAQ1qhE7ZiQmMAEpXMNQ2+5drQZQa6lkqIHcXEM4=
  bucket: zachhuxford-io
  skip_cleanup: true
  region: ap-southeast-2
  local-dir: build
  acl: public_read
  on:
    repo: zachbwh/zachhuxford.io
